#pragma once

#include "Constants.h"

#include <Resource.h>
#include <string>
#include <unordered_map>

struct BuffInfo
{
    int resourceID;
    std::string name; // for texture naming (prefixed with addon name)
};

inline std::unordered_map<int, BuffInfo> BuffDefs = {
    {BuffIds::GENERIC_ENHANCEMENT, {RC_GENERIC_ENHANCEMENT, "ENHANCEMENT"}},
    {BuffIds::GENERIC_SIGIL, {RC_GENERIC_SIGIL, "SIGIL"}},
    {BuffIds::GENERIC_FOOD, {RC_GENERIC_FOOD, "FOOD"}},

    // misc
    {BuffIds::SHARPENING_STONE, {RC_SHARPENING_STONE, "SHARPENING_STONE"}},

    // slaying
    {BuffIds::DREDGE_SLAYING, {RC_DREDGE_SLAYING, "DREDGE_SLAYING"}},
    {BuffIds::FLAME_LEGION_SLAYING, {RC_FLAME_LEGION_SLAYING, "FLAME_LEGION_SLAYING"}},
    {BuffIds::GHOST_SLAYING, {RC_GHOST_SLAYING, "GHOST_SLAYING"}},
    {BuffIds::INQUEST_SLAYING, {RC_INQUEST_SLAYING, "INQUEST_SLAYING"}},
    {BuffIds::NIGHTMARE_COURT_SLAYING, {RC_NIGHTMARE_COURT_SLAYING, "NIGHTMARE_COURT_SLAYING"}},
    {BuffIds::OUTLAW_SLAYING, {RC_OUTLAW_SLAYING, "OUTLAW_SLAYING"}},
    {BuffIds::UNDEAD_SLAYING, {RC_UNDEAD_SLAYING, "UNDEAD_SLAYING"}},
    {BuffIds::ICE_BROOD_SLAYING, {RC_ICE_BROOD_SLAYING, "ICE_BROOD_SLAYING"}},
    {BuffIds::DESTROYER_SLAYING, {RC_DESTROYER_SLAYING, "DESTROYER_SLAYING"}},
    {BuffIds::ELEMENTAL_SLAYING, {RC_ELEMENTAL_SLAYING, "ELEMENTAL_SLAYING"}},
    {BuffIds::DEMON_SLAYING, {RC_DEMON_SLAYING, "DEMON_SLAYING"}},
    {BuffIds::SONS_OF_SVANIR_SLAYING, {RC_SONS_OF_SVANIR_SLAYING, "SONS_OF_SVANIR_SLAYING"}},
    {BuffIds::SCARLETS_ARMIES_SLAYING, {RC_DEMON_SLAYING, "SCARLETS_ARMIES_SLAYING"}}, // shares icon with demon slaying

    // sigils
    {BuffIds::NIGHT_SIGIL, {RC_NIGHT_SIGIL, "NIGHT_SIGIL"}},
    {BuffIds::SERPENT_SIGIL, {RC_SERPENT_SIGIL, "SERPENT_SIGIL"}},
    {BuffIds::DEMON_SIGIL, {RC_DEMON_SIGIL, "DEMON_SIGIL"}},
};

